### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by keithmgould** [caffe2/reinforcement-learning-models#11]
Hi! Thanks SO much for putting this repo together.

Just pulled and in the tests (and in cart-pole example) getting same error:

```
    possible_next_actions: np.ndarray, reward_timelines, ds,
                         ^
SyntaxError: invalid syntax
```

I'm using:

0. Python 2.7.14
0. OSX

If it helps here was a full error from test:

```
======================================================================
ERROR: ml.rl.test.test_open_ai_gym (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: ml.rl.test.test_open_ai_gym
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "ml/rl/test/test_open_ai_gym.py", line 8, in <module>
    from ml.rl.test.gym.open_ai_gym_environment import OpenAIGymEnvironment
  File "ml/rl/test/gym/open_ai_gym_environment.py", line 10, in <module>
    from ml.rl.training.training_data_page import TrainingDataPage
  File "ml/rl/training/training_data_page.py", line 20
    possible_next_actions: np.ndarray, reward_timelines, ds,
                         ^
SyntaxError: invalid syntax
```

**Comment by nishadsingh1** [comment]
Hey @keithmgould, you are totally welcome!

I believe the issue is that you're running Python 2.x, and type hints require 3.5+: https://docs.python.org/3/library/typing.html

Do you mind upgrading your Python version and letting us know if you're still encountering the issue?

**Comment by keithmgould** [comment]
I see. I was under impression Caffe2 did not (at least officially) support Python 3.x? Their install page still pushes for 2.7 (with Anaconda, etc...). Would it be a major undertaking for me to fork your repo and make it 2.7 compatible?

**Comment by MisterTea** [comment]
@keithmgould caffe2 supports python 3 now.  The same instructions should work for both :-)

**Comment by keithmgould** [comment]
I'm going to close this, thanks for feedback everyone :)
